### ISSUE TITLE
CodeSignatureIdentifier update for XMind.download.recipe

### ISSUE THREAD

**Issue by ehjmx** [autopkg/ahousseini-recipes#12]
A client asked to add XMind to SelfService so I did an autopkg search and found your two recipes for download and pkg. Thanks for providing them. 

However when running the recipe I got an CodeSignatureVerifier error:
`Error in com.github.ahousseini-recipes.pkg.XMind: Processor: CodeSignatureVerifier: Error: Code signature verification failed. Note that all verifications can be disabled by setting the variable DISABLE_CODE_SIGNATURE_VERIFICATION to a non-empty value.`

I put XMind in Applications and run a codesign against it. It turns out that they changed the Signature to:
`identifier "net.xmind.vana.app" and anchor apple generic and certificate 1[field.1.2.840.113635.100.6.2.6] /* exists */ and certificate leaf[field.1.2.840.113635.100.6.1.13] /* exists */ and certificate leaf[subject.OU] = "4WV38P2X5K"`

I made a copy of your two recipes, changed the identifier for both, replaced the CodeSignatureVerifier requirement with the one above and I can now successfully build XMind. 

Hope this helps,
Eric

**Comment by ahousseini** [comment]
Thanks, I updated the recipe: https://github.com/autopkg/ahousseini-recipes/commit/fcb3ae95a14713e062c18f05a7d9933108532cf1
