### ISSUE TITLE
XMind.pkg.recipe - Use CFBundleShortVersionString string for Versioner

### ISSUE THREAD

**Issue by ehjmx** [autopkg/ahousseini-recipes#13]
After fixing the CodeSignatureVerifier error and being able to build XMind I got a pkg with 2022062417460 as the Version. That's the correct value of the given "CFBundleVersion" in Versioner in the pkg recipe and that's what I get for the downloaded dmg as well. 

Jamf Patch-Management uses the Version Number of "CFBundleShortVersionString" to determine if there is a newer version available. 

I did replace the "plist_version_key" string "CFBundleVersion" with "CFBundleShortVersionString" of the Versioner section in my copy of the recipe and ran it in combination with my modified download recipe.  I was able to successfully build XMind, getting no errors and XMind-12.0.3.pkg. 

Hope this helps, 
Eric

**Comment by ahousseini** [comment]
Thanks, I updated the recipe: https://github.com/autopkg/ahousseini-recipes/commit/fcb3ae95a14713e062c18f05a7d9933108532cf1
