### ISSUE TITLE
Aircall: No match found on URL 

### ISSUE THREAD

**Issue by listJg** [autopkg/ahousseini-recipes#5]
We are seeing the following error in Aircall.jss package:

Error: No match found on URL: https://electron.aircall.io/update/osx/0.0.0

**Comment by ahousseini** [comment]
This should be fixed, is it possible that your overrides are outdated?

**Comment by listJg** [comment]
I did create the override, but I did not update the repo  - this was causing the error. Now I have updated the repo and all is working very fine now.
Sorry for my dumminess!
Thank you for quick reply!

**Comment by ahousseini** [comment]
No problem, glad it worked :)
