### ISSUE TITLE
WOW. Synology recipe found!

### ISSUE THREAD

**Issue by pexner** [autopkg/ahousseini-recipes#7]
Hi there.
I stumbled over your Synology Drive recipe and how you solved using the release notes to extract the version number.
That's amazing!
Unfortunately, I'm not a coder at all and absolutely unable to do my own recipes.
Do you think, you could add the other Synology Desktop Apps to your recipes?
Synology Assistant
Synology Chat Client
Synology Note Station Client
Synology Hyper Backup Explorer

Will it be possible to make also .munki recipes from them?
A big thanks in advance,
Patrick

**Comment by ahousseini** [comment]
Hi Patrick

- Synology Assistent is not possible as the bundle has no version key in the `Info.plist`.
- Synology Chat is in the making but not public until the new AutoPkg version will be released with this approved PR: https://github.com/autopkg/autopkg/pull/739
- I created a download and pkg recipe for Synology Note Station, munki is not possible as I don't have a munki installation to test
- Synology Hyper Backup Explorer is not possible as the bundle has no version key in the `Info.plist`.

**Comment by pexner** [comment]
Oh. Wow. I knew that Synology's macOS apps are everything but standard apps. But this mess? Not even a correct Info.plist or version number in the bundle?
Hmm... We should send them a bugreport. :)
Anyway... Isn't it possible to use the version you found in the description and add it to the filename?
Like version 1.2.3 found and filename = SynologyApp-1.2.3.pkg

About your PR: Did you know, that pkgs from autopkg for munki use DASH "-" to separate the productname from the version number? AFAIK, Blabla_product_name_here-1.2.3.pkg. Like this, munki knows which version it is when importing.
Maybe i'm wrong?

PS: setting up a munki instance for testing became extremely easy. Just use MDS from here:
https://bitbucket.org/twocanoes/macdeploystick/downloads/
infos here: https://twocanoes.com/products/mac/mac-deploy-stick/
 Thanks in advance,
   Patrick

**Comment by mihelm** [comment]
We don't use Munki, so have no use for .munki recipes. Consequently, we don't provide any, because we wouldn't know when one of them develops an issue.

Cheers, michael.
