### ISSUE TITLE
SilhouetteStudio download recipe - not working 

### ISSUE THREAD

**Issue by paul-cossey** [autopkg/ahousseini-recipes#87]
Hi, @ahousseini 

The SilhouetteStudio download recipe has stopped working with the following error message 
```
Processor: SilhouetteStudioURLProvider: Error: Expecting value: line 1 column 1 (char 0)
```

I've taken a _super_ quick look just now, and the [App Cast URL](https://www.silhouetteamerica.com/ajax/?action=software/get_download_data&software=ss) returns a 403

**Comment by mihelm** [comment]
Hi @paul-cossey

Yes, they've changed up their website. The other day they just had a banner up that they were making improvements. Looks like they're done improving and we can now turn to fixing. ;-)

**Comment by mihelm** [comment]
Hi @paul-cossey 
I've updated the download recipe and it should now work again.
Cheers, michael.

**Comment by paul-cossey** [comment]
Thanks for the quick fix, @mihelm 🚀
